/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    AdminSection: typeof import('./src/components/AdminSection.vue')['default']
    ContentEditor: typeof import('./src/components/ContentEditor.vue')['default']
    DataEditor: typeof import('./src/components/DataEditor.vue')['default']
    Docs: typeof import('./src/components/Docs.vue')['default']
    EditorDrawer: typeof import('./src/components/EditorDrawer.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    ErrorPage: typeof import('./src/components/ErrorPage.vue')['default']
    FieldFieldItem: typeof import('./src/components/FieldFieldItem.vue')['default']
    FieldHeader: typeof import('./src/components/FieldHeader.vue')['default']
    FieldItem: typeof import('./src/components/FieldItem.vue')['default']
    FieldItemErrorTooltip: typeof import('./src/components/FieldItemErrorTooltip.vue')['default']
    FileFieldItem: typeof import('./src/components/FileFieldItem.vue')['default']
    FileManager: typeof import('./src/components/FileManager.vue')['default']
    GlobalComponents: typeof import('./src/components/GlobalComponents.vue')['default']
    GoogleSignInButton: typeof import('./src/components/GoogleSignInButton.vue')['default']
    ImgTag: typeof import('./src/components/ImgTag.vue')['default']
    InterfaceEditor: typeof import('./src/components/InterfaceEditor.vue')['default']
    InterfaceSelector: typeof import('./src/components/InterfaceSelector.vue')['default']
    IntroductionDialog: typeof import('./src/components/IntroductionDialog.vue')['default']
    JsonEditModal: typeof import('./src/components/JsonEditModal.vue')['default']
    JSONms: typeof import('./src/components/JSONms.vue')['default']
    ListBuilder: typeof import('./src/components/ListBuilder.vue')['default']
    LocaleSwitcher: typeof import('./src/components/LocaleSwitcher.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MigrationDialog: typeof import('./src/components/MigrationDialog.vue')['default']
    NewInterfaceModal: typeof import('./src/components/NewInterfaceModal.vue')['default']
    Prompt: typeof import('./src/components/Prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionPanel: typeof import('./src/components/SessionPanel.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SitePreview: typeof import('./src/components/SitePreview.vue')['default']
    Snack: typeof import('./src/components/Snack.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    TypingsModal: typeof import('./src/components/TypingsModal.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    WebhookManager: typeof import('./src/components/WebhookManager.vue')['default']
    WebhookManagerModal: typeof import('./src/components/WebhookManagerModal.vue')['default']
  }
}
