/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminSection: typeof import('./src/components/AdminSection.vue')['default']
    ContentEditor: typeof import('./src/components/ContentEditor.vue')['default']
    Docs: typeof import('./src/components/Docs.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    FieldList: typeof import('./src/components/FieldList.vue')['default']
    GlobalComponents: typeof import('./src/components/GlobalComponents.vue')['default']
    GoogleSignInButton: typeof import('./src/components/GoogleSignInButton.vue')['default']
    Integration: typeof import('./src/components/Integration.vue')['default']
    InterfaceEditor: typeof import('./src/components/InterfaceEditor.vue')['default']
    InterfaceSelector: typeof import('./src/components/InterfaceSelector.vue')['default']
    ListBuilder: typeof import('./src/components/ListBuilder.vue')['default']
    LocaleSwitcher: typeof import('./src/components/LocaleSwitcher.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Prompt: typeof import('./src/components/Prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionPanel: typeof import('./src/components/SessionPanel.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
  }
}
