/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/[interface]': RouteRecordInfo<'/admin/[interface]', '/admin/:interface', { interface: ParamValue<true> }, { interface: ParamValue<false> }>,
    '/admin/[interface]/': RouteRecordInfo<'/admin/[interface]/', '/admin/:interface', { interface: ParamValue<true> }, { interface: ParamValue<false> }>,
    '/admin/[interface]/[section]': RouteRecordInfo<'/admin/[interface]/[section]', '/admin/:interface/:section', { interface: ParamValue<true>, section: ParamValue<true> }, { interface: ParamValue<false>, section: ParamValue<false> }>,
    '/admin/[interface]/[section]/[locale]': RouteRecordInfo<'/admin/[interface]/[section]/[locale]', '/admin/:interface/:section/:locale', { interface: ParamValue<true>, section: ParamValue<true>, locale: ParamValue<true> }, { interface: ParamValue<false>, section: ParamValue<false>, locale: ParamValue<false> }>,
    '/editor/[interface]': RouteRecordInfo<'/editor/[interface]', '/editor/:interface', { interface: ParamValue<true> }, { interface: ParamValue<false> }>,
  }
}
