name: Deploy to FTP

on:
  push:
    branches:
      - master  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Defining environment variables
        env:
          VITE_SERVER_URL: https://dev.json.ms
          VITE_ADMIN_DEMO_URL: https://json.ms/admin
          INTERFACE_EDITOR_URL: https://json.ms
        run: |
          echo "Value of VITE_SERVER_URL is $VITE_SERVER_URL"
          echo "Value of VITE_ADMIN_DEMO_URL is $VITE_ADMIN_DEMO_URL"
          echo "Value of INTERFACE_EDITOR_URL is $INTERFACE_EDITOR_URL"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build-only  # Adjust this if your build command is different

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}  # Your FTP server
          username: ${{ secrets.FTP_USERNAME }}  # Store your FTP username in GitHub Secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Store your FTP password in GitHub Secrets
          local-dir: dist  # Adjust this to your build output directory
          server-dir: ${{ secrets.FTP_SERVER_PROD_PATH }}  # Adjust this to your desired server directory
